### ISSUE TITLE
Injection of HTML Junk

### ISSUE THREAD

**Issue by schmidhauser** [Arthur-Milchior/anki-Multi-column-edit-window#16]
Since Anki 2.1.35 or so, the addon surreptitiously injects a lot of unwanted HTML into one’s own cards. Say you have the following line

```
<p>x y</p>
```

Now place the cursor before y, and press the Return key and then the Delete key. In my case, the result is

```
<p>x&nbsp;<span style="color: var(--text-fg);">y</span></p>
```

I’m on macOS Mojave, with Anki 2.1.40. All other addons are deactivated.

**Comment by Arthur-Milchior** [comment]
Thank you very much for this report. Especially for finding a way to reproduce, that's extremely helpful!
Do you see any difference in the card or when you open the card in the browser later ?
I can reproduce. I've no idea what's going on, but clearly I'll need to correct that. Since it seems to be always the same

I've never heard of it before. I'll need to take a look. Not before this week-end at least.

**Comment by Nayelianne** [comment]
I'm very interested in this addon but got scared with all the comments about the html injections on ankiweb, so I figured I'd ask before installing... was this issue ever fixed?
